centroids: F:\DGM\code\HW3\data\mnist_centroids.npy
classify: false
embed_dim: 16
learning_rate: 0.003
num_classes: 10
num_heads: 2
num_layers: 8
num_pixels: 20
num_vocab: 16
steps: 100
warmup_steps: 10
